---
- hosts: all

  vars:
    apt_install_packages: ['apache2',
                           'apache2-utils',
                           'libapache2-mod-php5',
                           'php5']

  tasks:
    - name: update system packages...
      sudo: yes
      apt:
        cache_valid_time=86400
        update_cache=yes
        upgrade=safe
      ignore_errors: yes

    - name: install apt packages...
      sudo: yes
      apt: name="{{ item }}"
        update_cache=yes
        cache_valid_time=864000
        state=present
      with_items:
        - "{{ apt_install_packages }}"
