---
- hosts: all

  vars:
    apt_install_packages: ['apache2',
                           'apache2-utils',
                           'libapache2-mod-php5',
                           'php5']
    root_template_files: [{src: 'templates/000-default.conf', dest: '/etc/apache2/sites-available/000-default.conf'}]

  tasks:
    - name: update system packages...
      sudo: yes
      apt:
        cache_valid_time=86400
        update_cache=yes
        upgrade=safe
      ignore_errors: yes

    - name: install apt packages...
      sudo: yes
      apt: name="{{ item }}"
        update_cache=yes
        cache_valid_time=864000
        state=present
      with_items:
        - "{{ apt_install_packages }}"

    - name: templates that require root into place...
      sudo: yes
      template: src="{{ item.src }}" dest="{{ item.dest }}"
      with_items:
        - "{{ root_template_files }}"
